### PR TITLE
Hotfix/190 fix current user mock

### LINKED ISSUE #190: Hotfix for the mock current user problem
## Content:

Fixed the problem for the different teams to mock their role as a teacher in order to test routes

Relates to #160

### PR DESCRIPTION
**Pull request by Te4-Alexander-Nilsson-Melbostad**
## What issue did you implement or fix?
Fixed #190 

## Summary
- Refactored the authorization policies
- fixed the current user mock problems
- Tested the manual tests with postman for the Crud auth routes

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## How can this implementation be improved?
- maybe authorise so that only admins can delete loans and not both the admin and the user who created it, im not sure

### CODE REVIEW

File: backend/app/controllers/api/v1/users_controller.rb [hunk 1]
```diff
@@ -33,5 +27,7 @@ def update
     # Use callbacks to share common setup or constraints between actions.
     def set_user
       @user = User.find(params[:id])
+      p "This is the damn user"
```
Comment (TE4-william-bruun) [inline backend/app/controllers/api/v1/users_controller.rb]: Is printing this data necessary?

**Comment by itggot-linus-styren** [comment]
The backend unit tests seems to fail with `lent_by_id' for nil:NilClass`, can this be fixed?

File: backend/app/controllers/api/v1/loans_controller.rb [hunk 2]
```diff
@@ -2,12 +2,12 @@ class Api::V1::LoansController < ApplicationController
   before_action :set_loan, only: [:show, :update, :destroy]
 
   def index
-    render json: policy_scope(Loan.all)
+    render json: Loan.all
```
Comment (TE4-jacob-lundberg) [inline backend/app/controllers/api/v1/loans_controller.rb]: Were you supposed to remove the policy_scope so anyone can retrieve all loans?

File: backend/app/policies/loan_policy.rb [hunk 3]
```diff
@@ -2,7 +2,7 @@ class LoanPolicy < ApplicationPolicy
   attr_reader :user, :loan
   class Scope < Scope
```
Comment (TE4-jacob-lundberg) [inline backend/app/policies/loan_policy.rb]: This scope is currently not being used as far as I can see, check above comment.

File: backend/app/controllers/api/v1/users_controller.rb [hunk 4]
```diff
@@ -10,16 +10,10 @@ def show
     render json: @user
   end
 
-  def create
-    authorize @user
-    p @user
-    
-  end
-
   def update
```
Comment (TE4-jacob-lundberg) [inline backend/app/controllers/api/v1/users_controller.rb]: Several prints in this method, are they really needed?

File: backend/app/policies/loan_policy.rb (hunk 3 above)
Comment (TE4-jacob-lundberg) [reply backend/app/policies/loan_policy.rb]: This scope is still not being used as far as I can see, since you have updated/commented it to clarify I would expect it to be used. Is there a reason for this or am I missing something?

File: backend/app/policies/loan_policy.rb [hunk 5]
```diff
@@ -1,45 +1,44 @@
...
+  # This is the policy for showing all different loans, you either have to be an admin or the 
+  # person who created the loan in order to see the information about it
+
   def show?
-    unless user && user&.admin? && user.uid == loan.lent_by_id
-      loan.errors.add(:lent_by, "authorization failed")
-      return false
-    end
-    return true
+    user&.admin? || user.uid == record.lent_by_id
```
Comment (TE4-Daniel-Kull) [inline backend/app/policies/loan_policy.rb]:
```suggestion
    user&.admin? || user&.uid == record.lent_by_id
```
For safetys sake, maybe we should consider using the safe navigator operator on all of the user calls as a standard? What do you think? :)

File: backend/app/policies/loan_policy.rb [hunk 6]
```diff
@@ -1,45 +1,44 @@
...
+  # created the loan (Maybe change this to only be avaiable to the admin)
 
-  def delete?
-    unless user&.admin? && user.uid == loan.lent_by_id
-      loan.errors.add(:lent_by, "authorization failed")
-      return false
-    end
-    return true
+  def destroy?
+    user&.admin? || user.uid == record.lent_by_id
```
Comment (TE4-Daniel-Kull) [inline backend/app/policies/loan_policy.rb]:
```suggestion
    user&.admin? || user&.uid == record.lent_by_id
```

File: backend/app/policies/user_policy.rb [hunk 7]
```diff
@@ -10,19 +13,32 @@ def resolve
...
       user&.admin? || record&.uid == user&.uid
     end
 
+
+    # This is the policy for creating loans, you either have to be logged in or be a admin in 
+    # orde to create a loan
+
     def create?
-      user && user.admin?
+      user.admin?
```
Comment (TE4-emanuel-strom) [inline backend/app/policies/user_policy.rb]: Is it safe not to include an & operator here?
Same with update? and destroy?

**Comment by TE4-jacob-lundberg** [comment]
Merging because of 3 approvals
