### PR TITLE
162 Post empty resources

### LINKED ISSUE #162: Users can post empty resources
**Describe the bug**
Users can post empty resources e.g. no titles or barcode on a book

**To Reproduce**
1. Go to /add
2. Choose any resource
3. Click on submit

**Expected behavior**
Some sort of check when submitting and possibly an alert or snackbar

### PR DESCRIPTION
**Pull request by te4-gabriel-stark**
##  What issue did you implement or fix?
Fixed #162 

## Summary
- Added if statements in the frontend so that you no longer can post empty stuff to the database.
- Also created interfaces so that it would look nicer in the modules.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## How can this implementation be improved?
- Do more checks and maybe break it down to smaller parts.

### CODE REVIEW

File: frontend/src/components/CreateBookFormComponent.vue [hunk 1]
```diff
@@ -43,7 +43,9 @@
 
     private onSubmit(evt: Event) {
       evt.preventDefault();
-      BooksModule.create(this.form);
+      if (!!this.form.barcode && !!this.form.title_id && !!this.form.status) {
+        BooksModule.create(this.form);
+      }
       this.onReset();
```
Comment (TE4-Mattis-Abrahamsson) [inline frontend/src/components/CreateBookFormComponent.vue]:
```suggestion
      this.onReset();
      }
```

Maybe put inside the if so the inputs won't get cleared unless it is sucessfull

Comment (TE4-Mattis-Abrahamsson) [inline frontend/src/components/CreateBookFormComponent.vue]:
```suggestion
      this.onReset();
      }
```
Maybe put inside the if so the inputs won't get cleared unless it is sucessfull

File: frontend/src/components/CreateBookFormComponent.vue [hunk 2]
```diff
@@ -43,7 +43,9 @@
 
     private onSubmit(evt: Event) {
       evt.preventDefault();
-      BooksModule.create(this.form);
+      if (!!this.form.barcode && !!this.form.title_id && !!this.form.status) {
+        BooksModule.create(this.form);
+      }
```
Comment (TE4-Mattis-Abrahamsson) [inline frontend/src/components/CreateBookFormComponent.vue]:
```suggestion

```

File: frontend/src/components/LoaningForm.vue [hunk 3]
```diff
@@ -34,9 +34,11 @@ export default class LoaningForm extends Vue {
...
-      .then((loan: any) => this.$emit('loan-added', loan))
-      .catch((failure: any) => console.log(failure));
+    if (!!this.form.lent_by_id && !!this.form.loaned_by_id && !!this.form.book_id) {
+      LoansModule.create(this.form)
+        .then((loan: any) => this.$emit('loan-added', loan))
+        .catch((failure: any) => console.log(failure));
+    }
   }
 
   public onReset(evt: Event) {
```
Comment (TE4-Mattis-Abrahamsson) [inline frontend/src/components/LoaningForm.vue]: Does this clear the form after submit?

File: frontend/src/components/TitelForm.vue [hunk 4]
```diff
@@ -37,9 +37,11 @@ export default class TitleForm extends Vue {
...
-    .then((title: any) => this.$emit('title-added', title))
-    .catch((failure: any) => console.log(failure));
+    if (!!this.form.name && !!this.form.cost && !! this.form.isbn && !!this.form.title_type) {
+      TitlesModule.create(this.form)
+      .then((title: any) => this.$emit('title-added', title))
+      .catch((failure: any) => console.log(failure));
+    }
   }
 
   public onReset(evt: Event) {
```
Comment (TE4-Mattis-Abrahamsson) [inline frontend/src/components/TitelForm.vue]: Does this clear after submit?

File: frontend/src/store/modules/BooksModule.ts [hunk 5]
```diff
@@ -2,13 +2,26 @@ import Vue from 'vue';
 import { VuexModule, Module, Action, Mutation, getModule } from 'vuex-module-decorators';
 import store from '..';
 import BooksAPI from '../../api/books';
+import { ITitle } from './TitlesModule';
 import convertList from '../../helpers/convertArrayToNested';
 
 interface BookState {
```
Comment (TE4-Mattis-Abrahamsson) [inline frontend/src/store/modules/BooksModule.ts]:
```suggestion
interface IBookState {
```

File: frontend/src/components/LoaningForm.vue (hunk 3 above)
Comment (te4-gabriel-stark) [reply frontend/src/components/LoaningForm.vue]: Nope, will add

File: frontend/src/components/CreateBookFormComponent.vue (hunk 1 above)
Comment (te4-gabriel-stark) [reply frontend/src/components/CreateBookFormComponent.vue]: Correct, will fix!

File: frontend/src/components/LoaningForm.vue (hunk 3 above)
Comment (te4-gabriel-stark) [reply frontend/src/components/LoaningForm.vue]: Since this version of the file is using bootstrap i dont know how to preventDefault beforehand, hence I dont know how to call the function without the event... But when this is vuetify you can just type .prevent on the function call and you dont need to parse any params.

File: frontend/src/store/modules/BooksModule.ts (hunk 5 above)
Comment (te4-gabriel-stark) [reply frontend/src/store/modules/BooksModule.ts]: Nice catch!
