### PR TITLE
Fixed the Pundit CRUD authorization

### LINKED ISSUE #160: Importing and using Pundit for authorization
**DoD**
when the user is not granted access to routes unless they are authorised to do so

### PR DESCRIPTION
**Pull request by Te4-Alexander-Nilsson-Melbostad**
## What issue did you implement or fix?
Fixed #160 

## Summary

- created policies for the Cruds of loans and users
- Tested the implementations in Postman that should be integrated in the Yabs postman team 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Context:
Blocked by #179

### CODE REVIEW

File: backend/app/controllers/api/v1/users_controller.rb [hunk 1]
```diff
@@ -2,14 +2,23 @@ class Api::V1::UsersController < ApplicationController
...
 
+  def create
+    authorize @user
+    p @user
+    
+  end
+
   def update
+    authorize @user
+    p "passed authorization"
```
Comment (TE4-jacob-lundberg) [inline backend/app/controllers/api/v1/users_controller.rb]: This print shouldn't be needed.

File: backend/app/controllers/application_controller.rb [hunk 2]
```diff
@@ -1,12 +1,15 @@
...
   rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
 
   def current_user
-    return User.first if Rails.env.test?
+
+  return User.first if Rails.env.test?
     @_current_user ||= session[:current_user_id] &&
-     User.find_by(uid: session[:current_user_id])
+    User.find_by(uid: session[:current_user_id])
+    @_current_user
```
Comment (TE4-jacob-lundberg) [inline backend/app/controllers/application_controller.rb]: This last statement return is unnecessary as it will be returned above.
