### PR TITLE
The cypress test will now fail if the title is not actually created in the create title test

### LINKED ISSUE #389: Cypress test does not fail even though it should
### Description
The cypress test `Creates a title and reset the fields when added` does not fail if it does not succeed in adding a title.
The Post request never finishes, due to the test finishing before it is complete.

## 🔬 To Reproduce
1. Run cypress test `Creates a title and reset the fields when added`

### 💡 Additional context

The test needs to assure that the newly added title also appears in the list of titles. Or some other way verify that the post request actually succeeds.

### PR DESCRIPTION
**Pull request by te4-adrian-almetun-smeds**
## ⚙️ What issue did you implement or fix?
Fixes #389

## 📜 Summary
- The cypress test will now fail if the title is not actually created
- This will however fail our suit now, due to the actual implementation being broken

## 📝 Type of change

Please delete options that are not relevant.

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature or enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 This change requires a documentation update

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: frontend/cypress/integration/createTitleAndBooks.js [hunk 1]
```diff
@@ -10,13 +10,24 @@ describe('This test will create a title and a book', () => {
...
+    cy.get('[data-cy=isbn]').type(isbn);
     cy.get('[data-cy=titleType]').click({force:true});
     cy.get('div').contains('Kurslitteratur').click();
     cy.get('[data-cy=submit]').click();
+
+    cy.get('[data-jest=search]').type(bookTitle);
+    cy.get('[data-cy=table]').contains(bookTitle);
+
     cy.get('[data-cy=reset]').click();
+    cy.get('[data-cy=name]').should('have.not.value',bookTitle);
```
Comment (itggot-linus-styren) [inline frontend/cypress/integration/createTitleAndBooks.js:28]: Minor formatting comment
```suggestion
    cy.get('[data-cy=name]').should('have.not.value', bookTitle);
```

**Review by itggot-linus-styren — APPROVED** [review]
LGTM however you haven't setup https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/generating-a-new-gpg-key so I don't know if you really are Adrian ;)

You need to commit using "-S" or run git config --global commit.gpgsign true

**Review by Te4-Jacob-sandstrom — APPROVED** [review]
Looks good
