### PR TITLE
Bugfix/222/tests throw no method error

### LINKED ISSUE #222: Backend tests throws unexpected errors
## Description
Error: 'NoMethodError: undefined method `>' for nil:NilClass'
is thrown in tests for LoansController and UserController.

Error: Expected response to be a <2XX: success>, but was a <422: Unprocessable Entity>
## DoD
- Tests that should pass no longer throws errors.

### PR DESCRIPTION
**Pull request by TE4-emanuel-strom**
## What issue did you implement or fix?
Fixes #222 

## Summary
- Fixed bug that made backend tests throw an unexpected error.
- Also did some minor cleanup.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## How can this implementation be improved?
We should not use fixtures that are generated every time from the google API, instead hard code the fixtures we want to use for our backend tests.

### CODE REVIEW

File: backend/db/seeds.rb [hunk 1]
```diff
@@ -32,7 +32,7 @@
 
 loan_cc = Loan.new(expiration_date: Date.current)
 loan_cc.lent_by = User.find_by_name("Låneservice Johanneberg")
-loan_cc.loaned_by = User.first
+loan_cc.loaned_by = User.find(1975529089)
```
Comment (te4-david-petersson) [inline backend/db/seeds.rb]: Doesn't this only find one specific user?

Comment (TE4-jacob-lundberg) [reply backend/db/seeds.rb]: It should, User.first should be the preferred approach here as this user might not be here in a couple of years causing the tests to become outdated and fail.

Comment (TE4-emanuel-strom) [reply backend/db/seeds.rb]: Good point, but the whole problem was caused by the User who happened to be first was broken in some way and caused all User related tests to fail. Indeed the tests should optimaly be more resistant to the database changing, and that is why we need to hard code fixtures instead of dumping them from the database as we are doing now. That however is a separate issue outside the scope of this one.

**Comment by itggot-linus-styren** [comment]
Fix the errors with httparty by upgrading: https://github.com/jnunemaker/httparty/issues/681#issuecomment-566091726

File: backend/db/seeds.rb (hunk 1 above)
Comment (te4-david-petersson) [reply backend/db/seeds.rb]: Fair enough

File: backend/app/controllers/api/v1/users_controller.rb [hunk 2]
```diff
@@ -12,9 +12,9 @@ def index
   # controller for showing the user and also authorises in the same method, returns the
```
Comment (itggot-linus-styren) [inline backend/app/controllers/api/v1/users_controller.rb]: This doesn't correspond to the implementation below.

File: backend/app/controllers/api/v1/users_controller.rb [hunk 3]
```diff
@@ -12,9 +12,9 @@ def index
...
   # json object instance @user
 
-  def show
+  def show    
     authorize @user
-    render json: @user
+    render json: @users
```
Comment (itggot-linus-styren) [inline backend/app/controllers/api/v1/users_controller.rb]: Why does the show method return all users? See comment above.
