### PR TITLE
Bug/226 path argument error

### LINKED ISSUE #226: Lint throws "The "path" argument must be of type string. Received type undefined" error in github actions
**Describe the bug**
The linter throws an error preventing the linter from running.

**To Reproduce**
1. Push a commit
2. Wait for github actions
3. Unit > frontend-lint fails

**Expected behavior**
The lint runs correctly.

**Additional context**

### PR DESCRIPTION
**Pull request by TE4-jacob-lundberg**
## What issue did you implement or fix?
Fixes #226 

## Summary
- Added a package which the linter needed which was removed a couple PR:s back.
- Changed the default value of a prop to enable yarn build

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

## How can this implementation be improved?
- The current implementation of setting default value fixed the yarn build problem but might not work as intented.

### CODE REVIEW

File: frontend/src/components/SearchListComponent.vue [hunk 1]
```diff
@@ -44,7 +44,7 @@ export default class SearchListComponent extends Vue {
   public search: string = '';
   @Prop() public headers!: IHeader[];
   @Prop() public items!: any[]; // Please fix generic types.
-  @Prop({default: false}) public useActions: boolean;
+  @Prop() public useActions: boolean = false;
```
Comment (TE4-oskar-pilborg) [inline frontend/src/components/SearchListComponent.vue]: maybe works who knows? probably
