### PR TITLE
Guard against viewing sites while not logged in, redirects to error

### LINKED ISSUE #758: Routes should be inaccessible when not logged in
### Description
All routes except the landing page (/) should have v-if that checks if the user is logged in, just like what is being used in ProfileView.

### Expected behaviour
If the user is not logged in it shows an error message instead of the page.
## 🔬 To Reproduce
Steps to reproduce the behaviour:
1. Go to '/admin' (for example) without logging in
2. The default view shows, instead of a error message

### 📷 Screenshots
image

### PR DESCRIPTION
**Pull request by ntijoh-nikki-andersson**
## ⚙️ What issue did you implement or fix?
Fixes #758

## 📜 Summary
- Added a LogInView.vue
- Router.ts now guards attempts to access routes besides from / or /login 

## 📝 Type of change

Please delete options that are not relevant.

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ✨ New feature or enhancement (non-breaking change which adds functionality)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by olantig — APPROVED** [review]

File: frontend/src/router.ts [hunk 1]
```diff
@@ -42,12 +43,24 @@ const routes: RouteConfig[] = [
...
   mode: 'history',
   routes,
 };
-export default new VueRouter(options);
+const router = new VueRouter(options);
+export default router;
+
+router.beforeEach((to, from, next) => {
+  if (to.name !== 'login' && to.name !== 'start' && !UsersModule.currentUser) next({ name: 'login' });
+  //else if (to.name !== 'start' && !UsersModule.currentUser) next({ name: 'login' });
```
Comment (olantig) [inline frontend/src/router.ts:64]: I think you should remove out-commented code? Or not?

Comment (ntijoh-nikki-andersson) [reply frontend/src/router.ts:64]: Oooh I missed that!

**Review by olantig — APPROVED** [review]

**Review by ntijoh-linus-sjunnesson — APPROVED** [review]
+1
