### PR TITLE
Fixed 170 and you can now post the type.

### LINKED ISSUE #170: When adding Title the Option value do not show up in the table
**Describe the bug**
Happening when adding Title. 

**To Reproduce**
Add a title and option and you will see the table have not got any type of book.

**Expected behavior**
Show the type of book

**Screenshots**
Screenshot 2019-12-10 at 15 41 52

### PR DESCRIPTION
**Pull request by te4-gabriel-stark**
## What issue did you implement or fix?
Fixed #170 

## Summary
- You can now post what type of book it is.
- Added a interface for the title form so that the lint wouldn't scream at me.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: frontend/src/store/modules/TitlesModule.ts [hunk 1]
```diff
@@ -20,6 +20,13 @@ export interface Title {
   updated_at: string;
 }
 
+export interface TitleFormI {
```
Comment (TE4-jacob-lundberg) [inline frontend/src/store/modules/TitlesModule.ts]: When using I to name interfaces, aren't they supposed to prefix it? On an older PR you made I'm pretty sure you  prefixed it.

Comment (TE4-Mattis-Abrahamsson) [reply frontend/src/store/modules/TitlesModule.ts]: And we have decided not to use name them with I at all

Comment (te4-gabriel-stark) [reply frontend/src/store/modules/TitlesModule.ts]: Will fix this, used this because the file and class also was called TitleForm. But good input.
