### PR TITLE
Fixed test

### LINKED ISSUE #408: Testing for admin/cards
testing in cypress

### PR DESCRIPTION
**Pull request by te4-alexander-nylundgomes**
## ⚙️ What issue did you implement or fix?
Fixes #408 

## 📜 Summary
- Tests for admin/cards

## 📝 Type of change

Please delete options that are not relevant.

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)

## ✅ Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## 💩 How can this implementation be improved?
- More tests

### CODE REVIEW

File: frontend/cypress/integration/AdminCards.js [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+
+    it('Tries to select a user for the card', () => {
+        cy.get('[data-cy=user-selector]').click().first().click();
+        // cy.get('[data-cy=user-selector]').type('a').type('{enter}');
+        
+    })
+
+    it('Tries to download card', () => {
+        cy.get('[data-cy=download-btn]').click();
+        //Is there a way for cypress to check if file is being downloaded?
```
Comment (te4-adrian-almetun-smeds) [inline frontend/cypress/integration/AdminCards.js:32]: Are all of these comments required for this test to pass? 🤔

**Review by te4-adrian-almetun-smeds — CHANGES_REQUESTED** [review]
Looks good, I just had one question while reading this.

**Review by te4-henrik-stahl — APPROVED** [review]
Good job my guy! You managed to make an excellent code!
